environment:
  CMAKE_ARGS: ""

install:
  - appveyor DownloadFile http://slproweb.com/download/Win32OpenSSL-1_0_2.exe
  - Win32OpenSSL-1_0_2.exe /silent /verysilent /sp- /suppressmsgboxes
  - appveyor DownloadFile ftp://sourceware.org/pub/pthreads-win32/pthreads-w32-2-9-1-release.zip
  - md C:\pthreads
  - 7z e pthreads-w32-2-9-1-release.zip C:\pthreads

build:

build_script:
  - md build
  - cd build
  - cmake %CMAKE_ARGS% ..

cache:
  - C:\OpenSSL-Win32
  - C:\pthreads

